backend:
  name: github
  repo: boehs/cloud9
  branch: main
  site_domain: cloud9robotics.pages.dev
publish_mode: simple
media_folder: _public/media
public_folder: media
site_url: https://cloud9robotics.pages.dev
collections:
  - name: blog
    label: Blog
    folder: pages/blog
    create: true
    slug: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          default: "{{now}}",
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: marketing
    label: Marketing
    folder: pages
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
